theme: jekyll-theme-modernist
title: Welcome to the Homepage of TakeshiJay
description: This page is used to share with others my ultimate goals in computer science and what I hope to continue to learn throughout my journey in Software Engineering
