theme: jekyll-theme-modernist
title: Welcome to the Homepage of TakeshiJay
description: This page is used to share with others my ultimate goals in computer science and what I hope to continue to learn throughout my journey in CS
CurrentGoals: My current goals this summer is to create my own decentralized network and possible create my own cryptocurrency to share with the world.
Currently I have been having difficulties figuring out what I need to fix on to land the coding job I dream for which is why I have taken into my own hands
to work on such a large project by myself. All new contributors are welcome and I would be grateful for any support that comes my way. 

